# Generated by Django 4.2.4 on 2023-09-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_product_old_price'),
        ('app_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orderHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeOrderHistory', to='app_order.order')),
                ('orderProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeOrderProduct', to='app_shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeOrderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
