# Generated by Django 4.2.4 on 2023-09-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_completeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteOrder',
        ),
    ]
