# Generated by Django 4.2.4 on 2023-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
