# Generated by Django 4.2.4 on 2023-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_order_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentId',
            field=models.CharField(blank=True, max_length=564, null=True),
        ),
    ]
